version: '3.8'
services:
  chall:
    build: ./chall
    ports:
      - 28201:1337
    networks:
      - default
    deploy: {resources: {limits: {cpus: '1', memory: 512M}}}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'head -c1 </dev/tcp/127.0.0.1/1337 | grep \">\"'"]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s
networks:
  default:
